name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executes every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@latest
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Check if SVG was generated
        run: |
          if [ ! -f dist/snake.svg ]; then
            echo "SVG not generated!"
            exit 1
          fi

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@latest
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on success
        if: success()
        run: echo "Snake animation generated and pushed successfully!"
      
      - name: Notify on failure
        if: failure()
        run: echo "Failed to generate or push snake animation!"
